[package]
name = "noise-generator"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
rand = "0.8.5"
noise = { version = "0.8.2", features = ["images"] }

[profile.release]
opt-level = 3
debug = false
lto = true

